### ISSUE TITLE
synchronization beween the coroutines to maintain the order of execution in coroutines

### ISSUE THREAD

**Issue by sivasai-quartic** [ebb29c/asyncio-channel#2]
hello, I exploring this library, just checking whether this library suits my use case, I will have multiple coroutines that will get submitted or gathered to the asyncio run loop. the expectation is like,  if the first coroutine fails with some exception then I need the second coroutine should not get called (each coroutine is message in my case and it's should not be unordered or duplicate)? is it possible to achieve this with asyncio channels? 

Thanks

**Comment by ebb29c** [comment]
Hello, I am not sure that I understand your use case.  You want to put coroutine objects onto the channel?

**Comment by ebb29c** [comment]
Stale.  Closing
