### ISSUE TITLE
take() not exported

### ISSUE THREAD

**Issue by pahansen95** [ebb29c/asyncio-channel#3]
Looking at the API Docs I see [take()](https://github.com/ebb29c/asyncio-channel/blob/main/docs/api.md#take) has been documented but it doesn't seem to be [exported](https://github.com/ebb29c/asyncio-channel/blob/c1c5d0db8b58e3ed9c8274b1604dbda382657fa4/asyncio_channel/__init__.py#L3-L9).

Is this intentional?

**Comment by ebb29c** [comment]
Hi, thanks for reporting this.

It looks like `take()` was documented but has not yet been implemented.  Stay tuned

**Comment by ebb29c** [comment]
It was just a case of outdated docs: the function previously known as `take()` was renamed `itermerge()`
